# Generated by Django 5.2.5 on 2025-08-13 23:10

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalChatSession",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical chat session",
                "verbose_name_plural": "historical chat sessions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ToolCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("arguments", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(default="", max_length=60)),
                ("input_chars", models.IntegerField(default=0)),
                ("output_chars", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="chatmessage",
            options={},
        ),
        migrations.AlterModelOptions(
            name="chatsession",
            options={},
        ),
        migrations.AlterModelOptions(
            name="chatsummary",
            options={},
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="ended_at",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="title",
        ),
        migrations.RemoveField(
            model_name="chatsummary",
            name="in_progress",
        ),
        migrations.RemoveField(
            model_name="chatsummary",
            name="is_stale",
        ),
        migrations.RemoveField(
            model_name="chatsummary",
            name="last_message_id",
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chatsummary",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="chatsummary",
            name="model_used",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AlterField(
            model_name="chatsummary",
            name="raw_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="chatsummary",
            name="rewritten_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="chatsummary",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summaries",
                to="chatbot.chatsession",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="chatbot_cha_session_24e989_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsummary",
            index=models.Index(
                fields=["user", "updated_at"], name="chatbot_cha_user_id_97a0d6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatsummary",
            constraint=models.UniqueConstraint(
                fields=("user", "session"), name="uniq_summary_per_user_session"
            ),
        ),
        migrations.AddField(
            model_name="historicalchatsession",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalchatsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="toolcalllog",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tool_logs",
                to="chatbot.chatsession",
            ),
        ),
        migrations.AddField(
            model_name="toolcalllog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="usagelog",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chatbot.chatsession",
            ),
        ),
        migrations.AddField(
            model_name="usagelog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
