name: Bug Report
description: File a bug report
labels: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
